### ISSUE TITLE
A UserInput should be able to read in user input from the command line

### ISSUE THREAD

**Issue by leibmalina** [CSE237SP2022/project-passwordmanager-leib-ruby-jake-aaron#2]

**Comment by jakosowsky** [comment]
@AaronStein013 @rubygrant dealt with this issue on branch: https://github.com/CSE237SP2022/project-passwordmanager-leib-ruby-jake-aaron/tree/5-a-userinput-should-be-able-to-verify-that-the-input-os-of-a-certain-type-and-reprompt-the-user-if-it-is-not-the-desired-type
