### ISSUE TITLE
A PasswordRequirements class should be able to hold the user's password requirements

### ISSUE THREAD

**Issue by leibmalina** [CSE237SP2022/project-passwordmanager-leib-ruby-jake-aaron#7]

**Comment by leibmalina** [comment]
The (lowercase) letters should be the default, so we don't need a method to ask for this. Is there any chance you can remove this from the class? I'll just use the remainingLength instance variable to get the number of lowercase letters in the PasswordGenerator.

**Comment by leibmalina** [comment]
Also, the instance variables for the PasswordRequirements isn't accessible. Can you please make the instance variables public? Or creating getter methods for each would work as well.

**Comment by AaronStein013** [comment]
I'll make those changes asap, probably tonight or tomorrow. I'll pull request when it's done. Thanks for looking through it!
